language: clojure
before_install:
  # TODO: fix the structure and remove them
  - touch databases.edn
  - touch events.edn
script:
  - lein cljfmt check
  - lein kibit src test
  # FIXME: it throws an exeption
  # - lein eastwood
  - lein test
